### ISSUE TITLE
Failed to execute goal (analyze-dependencies) Dependency problem found

### ISSUE THREAD

**Issue by seriouscoderone** [gantsign/maven-archetypes#430]
No idea how to resolve this. 

I installed the archetype in vscode using the maven tools.

Just running `mvn clean install` results in this error

```
[WARNING] Unused declared dependencies found:
[WARNING]    org.slf4j:slf4j-simple:jar:1.7.26:runtime
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.621 s
[INFO] Finished at: 2020-04-11T11:44:43-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:analyze-only (analyze-dependencies) on project my-lib: Dependency problems found -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by freemanjp** [comment]
This is from the [maven-dependency-plugin](https://maven.apache.org/plugins/maven-dependency-plugin) [analyze-only](https://maven.apache.org/plugins/maven-dependency-plugin/analyze-only-mojo.html) goal.

Its purpose is to ensure good dependency hygiene by detecting dependencies in the wrong scope or dependencies that aren't used or are used but not declared.

The following guide should help you resolve the issue: [https://maven.apache.org/plugins/maven-dependency-plugin/examples/exclude-dependencies-from-dependency-analysis.html](https://maven.apache.org/plugins/maven-dependency-plugin/examples/exclude-dependencies-from-dependency-analysis.html).

If you just want to disable this check add `<mdep.analyze.skip>true</mdep.analyze.skip>` to your Maven properties.
